{% set name = "nakametpy" %}
{% set version = "2021.6.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3d5244fb3f7ef4fee3484d2298913c42d76de7e63689900eef4c322666e860e5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib >=3.0.0
    - nose >=1.1.0
    - numpy >=1.17.0
    - pip
    - python
  run:
    - matplotlib >=3.0.0
    - nose >=1.1.0
    - numpy >=1.17.0
    - python

test:
  imports:
    - nakametpy

about:
  home: "https://github.com/muchojp/NakaMetPy"
  license: BSD 3-clause
  license_family: BSD
  license_file: 
  summary: "Meteorological modules for calculation and colormap."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
